name: Build and test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y python3-numpy
      - run: make
      - run: make test
